DROP DATABASE IF EXISTS `fangdeniu`;

CREATE DATABASE IF NOT EXISTS `fangdeniu` DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_general_ci;

USE `fangdeniu`;

CREATE TABLE `article` (
  id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(100) NOT NULL DEFAULT '',
  content TEXT NOT NULL DEFAULT '',
  save_date TIMESTAMP NOT NULL DEFAULT current_timestamp
)